package ravendb

type WhereOperator int

const (
	WhereOperatorEquals WhereOperator = iota
	WhereOperatorNotEquals
	WhereOperatorGreaterThan
	WhereOperatorGreaterThanOrEqual
	WhereOperatorLessThan
	WhereOperatorLessThanOrEqual
	WhereOperatorIn
	WhereOperatorAllIn
	WhereOperatorBetween
	WhereOperatorSearch
	WhereOperatorLucene
	WhereOperatorStartsWith
	WhereOperatorEndsWith
	WhereOperatorExists
	WhereOperatorSpatialWithin
	WhereOperatorSpatialContains
	WhereOperatorSpatialDisjoint
	WhereOperatorSpatialIntersects
	WhereOperatorRegex
)
