package ravendb

type whereOperator int

const (
	whereOperatorEquals whereOperator = iota
	whereOperatorNotEquals
	whereOperatorGreaterThan
	whereOperatorGreaterThanOrEqual
	whereOperatorLessThan
	whereOperatorLessThanOrEqual
	whereOperatorIn
	whereOperatorAllIn
	whereOperatorBetween
	whereOperatorSearch
	whereOperatorLucene
	whereOperatorStartsWith
	whereOperatorEndsWith
	whereOperatorExists
	whereOperatorSpatialWithin
	whereOperatorSpatialContains
	whereOperatorSpatialDisjoint
	whereOperatorSpatialIntersects
	whereOperatorRegex
)
